# Generated by Django 3.2 on 2022-12-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='QR',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
